### ISSUE TITLE
Unable to access curator cluster

### ISSUE THREAD

**Issue by ajinkyababar** [operate-first/curator-operator#52]
I have created an issue thread for this in https://github.com/operate-first/support/issues and assigned it to @larsks.

Issue link - https://github.com/operate-first/support/issues/580

**Comment by skanthed** [comment]
The reason it didn't come up was they retired a machine that provide reverse DNS for the network where this server live on. Because of that when they came back up they could not set there correct system host name. So, they weren't able to form a cluster. For now (temporarily) the correct host name is set and restarted the services and they are working fine.
